matrix:
  include:

    - language: node_js
      node_js:
        - "node"
        - "iojs"
      install:
        - npm install -g codecov
      script:
        - npm install
        - npm run build:production
        - npm test
        - codecov

      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        verbose: true
        on:
          branch: master
        local-dir: dist
        target-branch: gh-pages
        verbose: true

      before_deploy:
        - zip -r deploy.zip package.json src/ public/
        - cd dist 
        - zip -r build.zip *
        - mv build.zip ../
        - cd ../
        - unzip -l deploy.zip 
        - unzip -l build.zip       
