matrix:
  include:

    - language: node_js
      node_js:
        - "node"
        - "iojs"
      before_script:
        - cd frontend
      install:
        - npm install -g codecov
      script:
        - npm install
        - npm run build
        - npm run test:unit
        - codecov

      deploy:
        - provider: lambda
        - access_key_id: "AKIAJI2AILVTDCY6H27Q"
        - secret_access_key: "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"
        - function_name: targetAppDeploy
        - region: us-east-1
        - handler_name: myHandler
        - runtime: nodejs4.3
        - publish: true 
        - #zip: index.js
        - zip: deploy.zip
        - role: "arn:aws:iam::664183912372:role/travis-deploy-lambda"
      on:
        - all_branches: true

      before_deploy:
        - zip -r deploy.zip package.json src/ public/

      after_deploy:
        - unzip -l deploy.zip 
