matrix:
  include:

    - language: node_js
      node_js:
        - "node"
        - "iojs"
      install:
        - npm install -g codecov
      script:
        - npm install
        - npm run build:production
        - npm test
        - codecov
        - npm run deploy
      # deploy:
      #   provider: pages
      #   skip-cleanup: true
      #   github-token: $GITHUB_TOKEN
      #   keep-history: true
      #   verbose: true
      #   on:
      #     all_branches: true
      #   local-dir: dist
      #   target-branch: gh-pages
      #   verbose: true
